-- DB_BAPBAKSA
-- CREATE DATABASE DB_BAPBAKSA;
USE DB_BAPBAKSA;

DROP TABLE IF EXISTS TBL_USER;
CREATE TABLE TBL_USER (
	u_no		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	u_id		VARCHAR(50) NOT NULL,
	u_pw		VARCHAR(200) NOT NULL,
	u_mail		VARCHAR(100) NOT NULL,
	u_phone		VARCHAR(50) NOT NULL,
	u_google_id	VARCHAR(100),
	u_status	INT NOT NULL DEFAULT 1,
	pi_no		INT,
	u_reg_date	TIMESTAMP DEFAULT NOW(),
	u_mod_date	TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS TBL_USER_STATUS;
CREATE TABLE TBL_USER_STATUS (
	u_status INT NOT NULL DEFAULT 1,
	u_status_name VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS TBL_USER_PROFILE_IMG;
CREATE TABLE TBL_USER_PROFILE_IMG (
	pi_no 		INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	pi_name 	VARCHAR(255) NOT NULL,
	u_no 		INT NOT NULL,
	pi_reg_date	TIMESTAMP DEFAULT NOW()
);

SELECT * FROM TBL_USER;
TRUNCATE TBL_USER;
DROP TABLE TBL_USER;

SELECT * FROM TBL_USER_STATUS;
TRUNCATE TBL_USER_STATUS;
DROP TABLE TBL_USER_STATUS;

SELECT * FROM TBL_USER_PROFILE_IMG;
TRUNCATE TBL_USER_PROFILE_IMG;
DROP TABLE TBL_USER_PROFILE_IMG;

