CREATE DATABASE DB_BAPBAKSA;
USE DB_BAPBAKSA;

DROP TABLE IF EXISTS TBL_USER;
CREATE TABLE TBL_USER (
	u_no		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	u_id		VARCHAR(50) NOT NULL,
	u_pw		VARCHAR(200) NOT NULL,
	u_mail		VARCHAR(100) NOT NULL,
	u_phone		VARCHAR(50) NOT NULL,
	u_google_id	VARCHAR(100),
	u_status	INT NOT NULL DEFAULT 1,
	pi_no		INT,
	u_reg_date	TIMESTAMP DEFAULT NOW(),
	u_mod_date	TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS TBL_USER_STATUS;
CREATE TABLE TBL_USER_STATUS (
	u_status INT NOT NULL DEFAULT 1,
	u_status_name VARCHAR(30) NOT NULL
);

DROP TABLE IF EXISTS TBL_USER_PROFILE_IMG;
CREATE TABLE TBL_USER_PROFILE_IMG (
	pi_no 		INT	NOT NULL AUTO_INCREMENT,
	pi_name 	VARCHAR(255) NOT NULL,
	u_no 		INT NOT NULL,
	pi_reg_date	TIMESTAMP DEFAULT NOW()
);


DROP TABLE IF EXISTS TBL_FRIDGE;
CREATE TABLE TBL_FRIDGE (
	u_no		INT	NOT NULL,
	ig_no		INT	NOT NULL,
	f_reg_date	TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS TBL_LIKE_RECIPE;
CREATE TABLE TBL_LIKE_RECIPE (
	u_no		INT	NOT NULL AUTO_INCREMENT,
	r_no		INT	NOT NULL,
	lr_reg_date	TIMESTAMP DEFAULT NOW()
);


DROP TABLE IF EXISTS TBL_ORDER;
CREATE TABLE TBL_ORDER (
	o_no			INT	NOT NULL AUTO_INCREMENT,
	o_id			VARCHAR(50)	NOT NULL,
	u_no			INT	NOT NULL,
	o_s_no			INT	NOT NULL DEFAULT 1,
	o_count			INT	NOT NULL,
	o_price			INT	NOT NULL,
	o_final_price	INT	NOT NULL,
	p_no			INT	NOT NULL,
	o_reg_date		TIMESTAMP DEFAULT NOW(),
	o_mod_date		TIMESTAMP DEFAULT NOW()
);


DROP TABLE IF EXISTS TBL_MARKET_CART;
CREATE TABLE TBL_MARKET_CART (
	mc_no			VARCHAR(255) NOT NULL AUTO_INCREMENT,
	u_no			INT	NOT NULL,
	i_no			INT	NOT NULL,
	mc_count		INT	DEFAULT 1,
	mc_reg_date		TIMESTAMP DEFAULT NOW(),
	mc_mod_date		TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS TBL_ORDER_STATUS;
CREATE TABLE TBL_ORDER_STATUS (
	o_s_no		INT	NOT NULL DEFAULT 1,
	o_s_name	VARCHAR(30)	NOT NULL
);


DROP TABLE IF EXISTS TBL_PUSH;
CREATE TABLE TBL_PUSH (
	p_no		INT	NOT NULL AUTO_INCREMENT,
	u_no		INT	NOT NULL,
	p_c_no		INT	NOT NULL,
	p_title		VARCHAR(100) NOT NULL,
	p_content	VARCHAR(255) NOT NULL,
	p_status	BOOLEAN DEFAULT FALSE,
	p_reg_date	TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS TBL_PUSH_CATE;
CREATE TABLE TBL_PUSH_CATE (
	p_c_no		INT	NOT NULL,
	p_c_name	VARCHAR(30)	NOT NULL
);

DROP TABLE IF EXISTS TBL_PAYMENT;
CREATE TABLE TBL_PAYMENT (
	p_no		INT	NOT NULL AUTO_INCREMENT,
	u_no		INT	NOT NULL,
	p_price		INT	NOT NULL,
	p_s_no		INT	NOT NULL DEFAULT 1,
	p_reg_date	TIMESTAMP DEFAULT NOW(),
	p_mod_date	TIMESTAMP DEFAULT NOW()
);

DROP TABLE IF EXISTS TBL_PAYMENT_STATUS;
CREATE TABLE TBL_PAYMENT_STATUS (
	p_s_no		INT	NOT NULL DEFAULT 1,
	p_s_name	VARCHAR(30)	NOT NULL
);