-- REST

SELECT * FROM REFRIGERATOR;
TRUNCATE REFRIGERATOR;
DROP TABLE REFRIGERATOR;

SELECT * FROM PRODUCT;
TRUNCATE PRODUCT;
DROP TABLE PRODUCT;

SELECT * FROM RECIPE_BASIC;
TRUNCATE RECIPE_BASIC;
DROP TABLE RECIPE_BASIC;

SELECT * FROM RECIPE_INGREDIENT;
TRUNCATE RECIPE_INGREDIENT;
DROP TABLE RECIPE_INGREDIENT;

SELECT * FROM RECIPE_PROGRESS;
TRUNCATE RECIPE_PROGRESS;
DROP TABLE RECIPE_PROGRESS;

SELECT * FROM RECIPE_REGION;
TRUNCATE RECIPE_REGION;
DROP TABLE RECIPE_REGION;

SELECT * FROM RECIPE_CATEGORY;
TRUNCATE RECIPE_CATEGORY;
DROP TABLE RECIPE_CATEGORY;