

SELECT * FROM TBL_USER;
TRUNCATE TBL_USER;
DROP TABLE TBL_USER;

SELECT * FROM TBL_USER_STATUS;
TRUNCATE TBL_USER_STATUS;
DROP TABLE TBL_USER_STATUS;

SELECT * FROM TBL_USER_PROFILE_IMG;
TRUNCATE TBL_USER_PROFILE_IMG;
DROP TABLE TBL_USER_PROFILE_IMG;

SELECT * FROM TBL_FRIDGE;
TRUNCATE TBL_FRIDGE;
DROP TABLE TBL_FRIDGE;

SELECT * FROM TBL_LIKE_RECIPE;
TRUNCATE TBL_LIKE_RECIPE;
DROP TABLE TBL_LIKE_RECIPE;

SELECT * FROM TBL_ORDER;
TRUNCATE TBL_ORDER;
DROP TABLE TBL_ORDER;

SELECT * FROM TBL_MARKET_CART;
TRUNCATE TBL_MARKET_CART;
DROP TABLE TBL_MARKET_CART;

SELECT * FROM TBL_ORDER_STATUS;
TRUNCATE TBL_ORDER_STATUS;
DROP TABLE TBL_ORDER_STATUS;

SELECT * FROM TBL_PUSH;
TRUNCATE TBL_PUSH;
DROP TABLE TBL_PUSH;

SELECT * FROM TBL_PUSH_CATE;
TRUNCATE TBL_PUSH_CATE;
DROP TABLE TBL_PUSH_CATE;

SELECT * FROM TBL_PAYMENT;
TRUNCATE TBL_PAYMENT;
DROP TABLE TBL_PAYMENT;

SELECT * FROM TBL_PAYMENT_STATUS;
TRUNCATE TBL_PAYMENT_STATUS;
DROP TABLE TBL_PAYMENT_STATUS;

-- REST
SELECT * FROM REFRIGERATOR;
TRUNCATE REFRIGERATOR;
DROP TABLE REFRIGERATOR;

SELECT * FROM PRODUCT;
TRUNCATE PRODUCT;
DROP TABLE PRODUCT;

SELECT * FROM RECIPE_BASIC;
TRUNCATE RECIPE_BASIC;
DROP TABLE RECIPE_BASIC;

SELECT * FROM RECIPE_INGREDIENT;
TRUNCATE RECIPE_INGREDIENT;
DROP TABLE RECIPE_INGREDIENT;

SELECT * FROM RECIPE_PROGRESS;
TRUNCATE RECIPE_PROGRESS;
DROP TABLE RECIPE_PROGRESS;

SELECT * FROM RECIPE_REGION;
TRUNCATE RECIPE_REGION;
DROP TABLE RECIPE_REGION;

SELECT * FROM RECIPE_CATEGORY;
TRUNCATE RECIPE_CATEGORY;
DROP TABLE RECIPE_CATEGORY;